---

- name: Install required packages for autoupdate
  apt:
    name: '{{ item }}'
    update_cache: yes
  with_items:
    - unattended-upgrades
    - update-notifier-common
    - sendmail

- name: Enable automatic update / upgrade
  copy:
    content: |
      APT::Periodic::Update-Package-Lists "1";
      APT::Periodic::Unattended-Upgrade "1";
    dest: /etc/apt/apt.conf.d/20auto-upgrades

- name: Configure unattended upgrades
  template:
    src: templates/50unattended-upgrades
    dest: /etc/apt/apt.conf.d/50unattended-upgrades

...
